### ISSUE TITLE
No resource identifier found for attribute 'msvHint'

### ISSUE THREAD

**Issue by CDanilo25** [claudiodegio/MsvSearch#14]
Hi! I'm trying to set the SearchView with some custom settings, so in my layout it is configured with "app:msvHint", "app:msvSearchBackground" and "app:msvTextColor".

The problem is that I can't compile because it generate "No resource identifier found for attribute [...] in package [...]".

How can I fix this?

(Also, there is a way to set an animation for the search bar closing?)

Thank you!

**Comment by claudiodegio** [comment]
Hi, 
I will check your problem, you use my library with jitpack ?
and what version ? 

For now it's not possibile to set animation to search bar closing, but any help are welcome 

regs
