### ISSUE TITLE
SuggestionMaterialSearchView: crash with a customer adapter

### ISSUE THREAD

**Issue by Gounlaf** [claudiodegio/MsvSearch#2]
Hi,

I'm using the `SuggestionMaterialSearchView` with a custom adapter ([FastAdapter](https://github.com/mikepenz/FastAdapter).
When cliking on item, the method `public void onItemClick(RecyclerView rv, View view, int position)` is invoked and produce a crash (because of casting adapter to `SearchSuggestRvAdapter`).

Right now, I don't find an "easy solution"; I need to create a custom View like `SuggestionMaterialSearchView`.

I might be able to do a PR to fix that, but I would like to have your advice / thoughts about the problem.

Thanks

**Comment by claudiodegio** [comment]
Hi, 

You can have 2 solution to the issue 

1 Extend SuggestionMaterialSearchView and ovverride the onItemClick method to solve quickly the issue 

2 Fix the issue using the an instanceof operator before the cast operation and if you fix the issue send me the PR.  

Thanks to use my view
